const categories = [
  { id: 'ART', name: '미술 / 공예' },
  { id: 'COOK', name: '요리 / 조리' },
  { id: 'INVEST', name: '투자 / 부업' },
  { id: 'LANGUAGE', name: '외국어' },
  { id: 'DESIGN', name: '디자인' },
  { id: 'BEAUTY', name: '패션 / 뷰티' },
  { id: 'PROGRAMMING', name: '프로그래밍' },
  { id: 'STARTUP', name: '창업' },
  { id: 'MUSIC', name: '음악' },
  { id: 'INTERIOR', name: '홈리빙 / 인테리어' },
  { id: 'EXAM', name: '시험 / 자격증' },
  { id: 'SPORTS', name: '스포츠' },
  { id: 'ACT', name: '연기 / 마술' },
  { id: 'PET', name: '펫 / 반려동물' },
  { id: 'CAREER', name: '커리어' },
  { id: 'HEALTH', name: '건강' },
  { id: 'DANCE', name: '댄스' },
  { id: 'TRAVEL', name: '여행' },
  { id: 'STUDY', name: '학문' },
  { id: 'RELATIONSHIP', name: '인간관계' },
  { id: 'LIFE', name: '라이프' },
  { id: 'MEDIA', name: '사진 / 영상' },
  { id: 'HOBBY', name: '취미 생활' },
  { id: 'ETC', name: '기타' },
];

export default categories;
